import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientBody from "./ClientBody";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body suppressHydrationWarning className="antialiased">
        <ClientBody>
          <nav className="w-full py-4 px-6 flex justify-between items-center bg-white border-b shadow-sm">
            <Link href="/" className="font-bold text-primary text-xl">BESD Acquisition</Link>
            <div className="flex items-center gap-5">
              {session?.user ? (
                <>
                  <Link href="/dashboard" className="hover:underline">Dashboard</Link>
                  <form action="/api/auth/signout" method="POST" className="inline">
                    <button type="submit" className="text-primary underline hover:no-underline ml-2">Logout</button>
                  </form>
                </>
              ) : (
                <Link href="/login" className="hover:underline">Login</Link>
              )}
            </div>
          </nav>
          {children}
        </ClientBody>
      </body>
    </html>
  );
}
